version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    working_dir: /app
    volumes:
      - ./mlruns:/mlruns
      - ./app:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --no-cache-dir mlflow &&
             mlflow server
             --backend-store-uri sqlite:///mlflow.db
             --default-artifact-root /mlruns
             --host 0.0.0.0 --port 5000"
    restart: unless-stopped

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_notebook
    working_dir: /app
    volumes:
      - ./app:/app   # изменения в коде сразу подхватываются
    ports:
      - "8888:8888"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped
